### PR TITLE
urls checked before being submitted for purging

### PR DESCRIPTION
**Pull request by neetumorwani**

### CODE REVIEW

**Comment by neetumorwani** [comment]
@cam8001 @nerdstein Can you please help here in code review?
Link of the issue - https://github.com/d8-contrib-modules/akamai/issues/42

**Comment by cam8001** [comment]
Will take a look in the next hour or so.

**Comment by neetumorwani** [comment]
PR updated with the changes.

**Comment by neetumorwani** [comment]
PR updated with the changes.

**Comment by neetumorwani** [comment]
@cam8001 Format plural used in the code.
Thanks for the suggestion. It is awesome. :)

**Comment by cam8001** [comment]
Looks good, thanks!

**Pull request merged**
