### PR TITLE
Added Homepage Cache clear tests.

### PR DESCRIPTION
**Pull request by naveenvalecha**
Added Homepage Cache clear tests.

### CODE REVIEW

**Comment by naveenvalecha** [comment]
This test the akamai cache clear block is placed on the homepage

**Comment by naveenvalecha** [comment]
> Could we update the comment and assert text to be a little clearer?

Any suggestions on better text ?

**Comment by cam8001** [comment]
Let's merge it in and I'll update the comments on head

**Comment by nerdstein** [comment]
@cam8001 - @naveenvalecha - feel free to Skype me as needed (nerdstein) for reviews and/or assistance

**Pull request merged**
