### PR TITLE
Valid URL checks added in AkamaiClient

### PR DESCRIPTION
**Pull request by neetumorwani**

### CODE REVIEW

**Comment by neetumorwani** [comment]
@cam8001 @nerdstein Can you please help me here with the code review?
Thanks!

**Comment by cam8001** [comment]
Hey @neetumorwani, I was just working on something locally and had this form validation code error out.

Can you try with these values in the form please?

```
http://d8cdn.com/node/11
node/11
node/777
```

The first two should validate, the third should fail.

**Comment by neetumorwani** [comment]
@cam8001 Suggestions appreciated. Thanks.
PR updated.

**Comment by cam8001** [comment]
Just tested locally with the following URLs:

```
node/11
/node/11
```

A failure came back from the API:

`supportId: 17PY1457611197597933-414205120 title: unauthorized arl httpStatus: 403 detail: http://d8cdn.comnode/11 describedBy: https://api.ccu.akamai.com/ccu/v2/errors/unauthorized-arl`

Both of those should work.

**Comment by neetumorwani** [comment]
@cam8001 I have updated the PR. Can you please test the PR again.
[https://github.com/neetumorwani/akamai/commit/561113427c2162c06b7863220db52666ec404d24](url) 
admin/config/development/performance/akamai-cache-clear I have trimmed the '/' if it is entered by the user, Because otherwise '/' makes a relative URL(/node/1) an invalid URL. Not sure if we should be handling this case. Looking forward for the suggestion here.
Thanks!

**Comment by cam8001** [comment]
Tested locally, working well. Gonna go ahead and merge. Do you think you could write some test cases as a follow up?

Cheers!

**Pull request merged**
